### ISSUE TITLE
Username and password in application.properties

### ISSUE THREAD

**Issue by TomFairbairnSolace** [solacese/jms-hello-world#1]
You have your cloud plan username, password and host in application.properties.  These should be generic, so that a user can see these need to be set before running.

**Comment by Ushnash** [comment]
> 
> 
> You have your cloud plan username, password and host in application.properties. These should be generic, so that a user can see these need to be set before running.

Good point. I left them in there because I destroyed the instance shortly after finishing the demo.

The username is generic & the password random enough to where I doubt a (normal) person could guess the generator algorithm 😋
